### ISSUE TITLE
Functions from <math.h> are unparsing with std::

### ISSUE THREAD

**Issue by jvandebon** [ckiddo74/artisan#1]
If we have the following program, math.cpp:
```
#include <math.h>
int main(){
    float x, y;
    x = 5.5;
    y = sqrt(fabs(x));
}
```
And the following artisan meta-program, meta.py
```python3
#!/usr/bin/env artisan
from artisan.core import *
from artisan.rose import *

ast = model(args=cli())
ast.print()
```
We get the output:

```
/* TOP:/workspace/math.cpp */
#include <math.h>

int main() {
   float x;
   float y;
   x = 5.5;
   y = std::sqrt((std::fabs(x)));
}

/* BOTTOM:/workspace/math.cpp */
```

The math functions are prepended with ```std::``` and the resulting .cpp program will not compile.

**Comment by ckiddo74** [comment]
Jessica, can you replace <math.h> to <cmath> (no .h), and see if it works? 

Seems like the use of <math.h> is deprecated for C++ programs.

**Comment by jvandebon** [comment]
For this smple example, replacing with cmath works. I checked the more complicated program where I ran into this error, and I realised they are  ```using namespace std;```. So, even when using ```<cmath>```, the functions get unparsed with ```std::```.

So, for example, with the following C++ program:
```#include <cmath>
#include <fstream>

using namespace std;

int main(){
    float x, y;
    string my_string;
    x = 5.5;
    y = sqrt(fabs(x));
}
```

And this metaprogram:
```python3 
ast = model(args=cli())
ast.print()
```
The result is:
```
#include <cmath>
#include <fstream>
using namespace std;

int main() {
   float x;
   float y;
   std::__cxx11::string my_string;
   x = 5.5;
   y = std::sqrt((std::fabs(x)));
}
```

**Comment by ckiddo74** [comment]
Those math functions are supposed to be part of the `std` namespace in C++.

Where is it failing?

**Comment by jvandebon** [comment]
It works with g++ but not with the HLS compiler, which has it's own "HLS/math.h" header. For example, the following:

```
#include "HLS/math.h"
#include <cstdint>

#define OCL_ADDRSP_CONSTANT const __attribute__((address_space(2)))
#define OCL_ADDRSP_GLOBAL __attribute__((address_space(1)))
#define OCL_ADDRSP_PRIVATE __attribute__((address_space(0)))
#define OCL_ADDRSP_LOCAL __attribute__((address_space(3)))

extern "C" {
   void lib_func(int N, OCL_ADDRSP_GLOBAL float *in, OCL_ADDRSP_GLOBAL float *out) {
        for (uint64_t i = 0;  < N; i) {
            out[i] = std::sqrt(std::fabs(in[i]));
        }
    }
}
```

**Comment by ckiddo74** [comment]
This is an incompatibility with the HLS tools. Hopefully we can solve with the pragma approach. See #1.
