### ISSUE TITLE
Attributes are not being included in the ast

### ISSUE THREAD

**Issue by jvandebon** [ckiddo74/artisan#7]
With the following C++ program:
```
#define OCL_ADDRSP_GLOBAL __attribute__((address_space(1)))

extern "C" void lib_func(int n, OCL_ADDRSP_GLOBAL float *in, OCL_ADDRSP_GLOBAL float *out) {
   for (int i = 0; i < n; i++) {
      out[i] = in[i]*2;
   }
}
```
And this Artisan metaprogram:
```python3
#!/usr/bin/env artisan
from artisan.core import *
from artisan.rose import *

ast = model(args=cli())
ast.print()
```

The result is:
```
#define OCL_ADDRSP_GLOBAL __attribute__((address_space(1)))

void lib_func(int n,float *in,float *out) {
   for (int i = 0; i < n; i++) {
      out[i] = in[i] * 2;
   }
}
```
The ```OCL_ADDRSP_GLOBAL``` tag for each function parameter is removed, as well as the ```extern "C"``` declaration. So the resulting committed and exported code no longer compiles.

**Comment by ckiddo74** [comment]
This seems like a ROSE limitation:
https://github.com/rose-compiler/rose/issues/65

I will see what can be done, but is it possible for us to generate the "OpenCL" host code as the last step, without having to unparse it again?

**Comment by jvandebon** [comment]
This is in the .cpp file being compiled with HLS, so each time we modify it (i.e. changing the unroll factor during a design space exploration) it needs to be unparsed. For now, I am using string search to manually re-insert the attribute for all pointer parameters every time the code is re-generated.

**Comment by ckiddo74** [comment]
In regards to extern "C", while the code is correct, ROSE seems to have a problem with function definitions. So, instead of:

```
extern "C" void lib_func(...) {
   for (int i = 0; i < n; i++) {
      out[i] = in[i]*2;
   }
}
```
Try enclosing one or more function definitions (=function declaration + body) inside the extern "C".

```C++
extern "C" {

void lib_func(...) {
   for (int i = 0; i < n; i++) {
      out[i] = in[i]*2;
   }
}

} 
```
Let me know if it works. I will check the other issue.

**Comment by ckiddo74** [comment]
As discussed, ROSE does not seem to support the attributes required for Intel HLS compiler, so it would be best to use the pragma approach to optimise the kernel,  and then use a code gen meta-program that generates C++ code compatible with the HLS tools from the pragma annotations.
