### ISSUE TITLE
#pragma statements

### ISSUE THREAD

**Issue by jvandebon** [ckiddo74/artisan#8]
Is there a way to query for  ```#pragma``` statements and their associated blocks?

**Comment by ckiddo74** [comment]
The latest version supports the `Pragma` entity. 

- Once you find the Pragma node, you can use the `directive()` method to get the associated string.

- You can use the `next()` method to give you the associated node (next sibling). 

- The `next()` and `prev()` are part of Node entity, and therefore can be used for any AST node.

Let me know if you have any issues.
